In [1]:
import numpy as np 
arr1 = np.array([10,20,30,40,50]) 
print(arr1)
print(type(arr1)) 

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])  
print(arr)
print(arr[0])

[1 2 3 4 5]
1


In [4]:
import numpy as np 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr) 
print(arr[1][1]) 
print(arr[1])

[[1 2 3]
 [4 5 6]]
5
[4 5 6]


In [5]:
import numpy as np 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr.ndim)

2


In [6]:
import numpy as np 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr.itemsize)

4


In [7]:
import numpy as np 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr.dtype)

int32


In [8]:
import numpy as np 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr.size) 
print(arr.shape)

6
(2, 3)


In [9]:
import numpy as np 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
a=arr.reshape(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
import numpy as np 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr[0:,2]) 

[3 6]


In [12]:
import numpy as np 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr.min())
print(arr.max())
print(arr.sum())

1
6
21


In [14]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[1:5]) 
print(arr[4:]) 
print(arr[:4]) 
print(arr[-3:-1]) 
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [15]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(np.sqrt(arr))
print(np.std(arr))


[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
1.707825127659933


In [16]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print("vstack:",np.vstack((arr1,arr2)))
print("hstack:",np.hstack((arr1,arr2)))

vstack: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
hstack: [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [18]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(np.ravel(arr))

[1 2 3 4 5 6]


In [19]:
import numpy as np
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45])
i = np.where(arr == 30)
print(i)

(array([2], dtype=int32),)


In [21]:
import numpy as np  
arr=np.array([[1,4,2,3],[9,13,61,1],[43,24,88,22]])  
sort_arr=np.sort(arr)  
print(sort_arr)

[[ 1  2  3  4]
 [ 1  9 13 61]
 [22 24 43 88]]
